name: dc-testsuite-kob

services:
  kob-testsuite:
    image: gematik1/kob-testsuite:2.0.1
    container_name: kob-testsuite

    network_mode: host
    user: root

    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${TESTSUITE_TESTS}
      - KOB_STARTBROWSER=false
      - KOB_PSURL=http://host.docker.internal:8080
      - KOB_ASURL=https://host.docker.internal:8443

    volumes:
      - ./tiger.yaml:/app/tiger.yaml:ro
      - ./kob.yaml:/app/kob.yaml:ro
      - ./settings.xml:/home/kobtest/.m2/settings.xml:ro
      - kob-testsuite-maven:/home/kobtest/.m2/repository/:rw
      - kob-testsuite-report:/app/report/:rw

volumes:
  kob-testsuite-maven:
    name: kob-testsuite-maven
  kob-testsuite-report:
    name: kob-testsuite-report

